package com.csoft.resource.cflow.pojo;

import java.util.Date;

public class CfHistoryInstanceProcess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_history_instance_process.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_history_instance_process.process_instance_id
     *
     * @mbggenerated
     */
    private Long processInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_history_instance_process.process_id
     *
     * @mbggenerated
     */
    private String processId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_history_instance_process.process_name
     *
     * @mbggenerated
     */
    private String processName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_history_instance_process.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_history_instance_process.startTime
     *
     * @mbggenerated
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_history_instance_process.startUser
     *
     * @mbggenerated
     */
    private Long startuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_history_instance_process.currentTask
     *
     * @mbggenerated
     */
    private String currenttask;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_history_instance_process.id
     *
     * @return the value of cf_history_instance_process.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_history_instance_process.id
     *
     * @param id the value for cf_history_instance_process.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_history_instance_process.process_instance_id
     *
     * @return the value of cf_history_instance_process.process_instance_id
     *
     * @mbggenerated
     */
    public Long getProcessInstanceId() {
        return processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_history_instance_process.process_instance_id
     *
     * @param processInstanceId the value for cf_history_instance_process.process_instance_id
     *
     * @mbggenerated
     */
    public void setProcessInstanceId(Long processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_history_instance_process.process_id
     *
     * @return the value of cf_history_instance_process.process_id
     *
     * @mbggenerated
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_history_instance_process.process_id
     *
     * @param processId the value for cf_history_instance_process.process_id
     *
     * @mbggenerated
     */
    public void setProcessId(String processId) {
        this.processId = processId == null ? null : processId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_history_instance_process.process_name
     *
     * @return the value of cf_history_instance_process.process_name
     *
     * @mbggenerated
     */
    public String getProcessName() {
        return processName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_history_instance_process.process_name
     *
     * @param processName the value for cf_history_instance_process.process_name
     *
     * @mbggenerated
     */
    public void setProcessName(String processName) {
        this.processName = processName == null ? null : processName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_history_instance_process.version
     *
     * @return the value of cf_history_instance_process.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_history_instance_process.version
     *
     * @param version the value for cf_history_instance_process.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_history_instance_process.startTime
     *
     * @return the value of cf_history_instance_process.startTime
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_history_instance_process.startTime
     *
     * @param starttime the value for cf_history_instance_process.startTime
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_history_instance_process.startUser
     *
     * @return the value of cf_history_instance_process.startUser
     *
     * @mbggenerated
     */
    public Long getStartuser() {
        return startuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_history_instance_process.startUser
     *
     * @param startuser the value for cf_history_instance_process.startUser
     *
     * @mbggenerated
     */
    public void setStartuser(Long startuser) {
        this.startuser = startuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_history_instance_process.currentTask
     *
     * @return the value of cf_history_instance_process.currentTask
     *
     * @mbggenerated
     */
    public String getCurrenttask() {
        return currenttask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_history_instance_process.currentTask
     *
     * @param currenttask the value for cf_history_instance_process.currentTask
     *
     * @mbggenerated
     */
    public void setCurrenttask(String currenttask) {
        this.currenttask = currenttask == null ? null : currenttask.trim();
    }
}