package com.csoft.resource.cflow.pojo;

public class CfInstanceInputValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_instance_input_value.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_instance_input_value.process_instace_id
     *
     * @mbggenerated
     */
    private Long processInstaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_instance_input_value.process_id
     *
     * @mbggenerated
     */
    private String processId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_instance_input_value.process_name
     *
     * @mbggenerated
     */
    private String processName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_instance_input_value.cf_key
     *
     * @mbggenerated
     */
    private String cfKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_instance_input_value.cf_key_type
     *
     * @mbggenerated
     */
    private String cfKeyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_instance_input_value.cf_value
     *
     * @mbggenerated
     */
    private String cfValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_instance_input_value.id
     *
     * @return the value of cf_instance_input_value.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_instance_input_value.id
     *
     * @param id the value for cf_instance_input_value.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_instance_input_value.process_instace_id
     *
     * @return the value of cf_instance_input_value.process_instace_id
     *
     * @mbggenerated
     */
    public Long getProcessInstaceId() {
        return processInstaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_instance_input_value.process_instace_id
     *
     * @param processInstaceId the value for cf_instance_input_value.process_instace_id
     *
     * @mbggenerated
     */
    public void setProcessInstaceId(Long processInstaceId) {
        this.processInstaceId = processInstaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_instance_input_value.process_id
     *
     * @return the value of cf_instance_input_value.process_id
     *
     * @mbggenerated
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_instance_input_value.process_id
     *
     * @param processId the value for cf_instance_input_value.process_id
     *
     * @mbggenerated
     */
    public void setProcessId(String processId) {
        this.processId = processId == null ? null : processId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_instance_input_value.process_name
     *
     * @return the value of cf_instance_input_value.process_name
     *
     * @mbggenerated
     */
    public String getProcessName() {
        return processName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_instance_input_value.process_name
     *
     * @param processName the value for cf_instance_input_value.process_name
     *
     * @mbggenerated
     */
    public void setProcessName(String processName) {
        this.processName = processName == null ? null : processName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_instance_input_value.cf_key
     *
     * @return the value of cf_instance_input_value.cf_key
     *
     * @mbggenerated
     */
    public String getCfKey() {
        return cfKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_instance_input_value.cf_key
     *
     * @param cfKey the value for cf_instance_input_value.cf_key
     *
     * @mbggenerated
     */
    public void setCfKey(String cfKey) {
        this.cfKey = cfKey == null ? null : cfKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_instance_input_value.cf_key_type
     *
     * @return the value of cf_instance_input_value.cf_key_type
     *
     * @mbggenerated
     */
    public String getCfKeyType() {
        return cfKeyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_instance_input_value.cf_key_type
     *
     * @param cfKeyType the value for cf_instance_input_value.cf_key_type
     *
     * @mbggenerated
     */
    public void setCfKeyType(String cfKeyType) {
        this.cfKeyType = cfKeyType == null ? null : cfKeyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_instance_input_value.cf_value
     *
     * @return the value of cf_instance_input_value.cf_value
     *
     * @mbggenerated
     */
    public String getCfValue() {
        return cfValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_instance_input_value.cf_value
     *
     * @param cfValue the value for cf_instance_input_value.cf_value
     *
     * @mbggenerated
     */
    public void setCfValue(String cfValue) {
        this.cfValue = cfValue == null ? null : cfValue.trim();
    }
}