package com.csoft.resource.cflow.pojo;

import java.util.Date;

public class CfInstanceTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_instance_task.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_instance_task.process_instace_id
     *
     * @mbggenerated
     */
    private Long processInstaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_instance_task.task_id
     *
     * @mbggenerated
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_instance_task.task_name
     *
     * @mbggenerated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_instance_task.process_id
     *
     * @mbggenerated
     */
    private Long processId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_instance_task.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_instance_task.create_user
     *
     * @mbggenerated
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_instance_task.execute_result
     *
     * @mbggenerated
     */
    private String executeResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_instance_task.id
     *
     * @return the value of cf_instance_task.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_instance_task.id
     *
     * @param id the value for cf_instance_task.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_instance_task.process_instace_id
     *
     * @return the value of cf_instance_task.process_instace_id
     *
     * @mbggenerated
     */
    public Long getProcessInstaceId() {
        return processInstaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_instance_task.process_instace_id
     *
     * @param processInstaceId the value for cf_instance_task.process_instace_id
     *
     * @mbggenerated
     */
    public void setProcessInstaceId(Long processInstaceId) {
        this.processInstaceId = processInstaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_instance_task.task_id
     *
     * @return the value of cf_instance_task.task_id
     *
     * @mbggenerated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_instance_task.task_id
     *
     * @param taskId the value for cf_instance_task.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_instance_task.task_name
     *
     * @return the value of cf_instance_task.task_name
     *
     * @mbggenerated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_instance_task.task_name
     *
     * @param taskName the value for cf_instance_task.task_name
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_instance_task.process_id
     *
     * @return the value of cf_instance_task.process_id
     *
     * @mbggenerated
     */
    public Long getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_instance_task.process_id
     *
     * @param processId the value for cf_instance_task.process_id
     *
     * @mbggenerated
     */
    public void setProcessId(Long processId) {
        this.processId = processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_instance_task.start_time
     *
     * @return the value of cf_instance_task.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_instance_task.start_time
     *
     * @param startTime the value for cf_instance_task.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_instance_task.create_user
     *
     * @return the value of cf_instance_task.create_user
     *
     * @mbggenerated
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_instance_task.create_user
     *
     * @param createUser the value for cf_instance_task.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_instance_task.execute_result
     *
     * @return the value of cf_instance_task.execute_result
     *
     * @mbggenerated
     */
    public String getExecuteResult() {
        return executeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_instance_task.execute_result
     *
     * @param executeResult the value for cf_instance_task.execute_result
     *
     * @mbggenerated
     */
    public void setExecuteResult(String executeResult) {
        this.executeResult = executeResult == null ? null : executeResult.trim();
    }
}