package com.csoft.resource.cflow.pojo;

public class RmService {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_service.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_service.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_service.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_service.alias
     *
     * @mbggenerated
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_service.typeId
     *
     * @mbggenerated
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rm_service.displayOrder
     *
     * @mbggenerated
     */
    private Integer displayorder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_service.Id
     *
     * @return the value of rm_service.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_service.Id
     *
     * @param id the value for rm_service.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_service.name
     *
     * @return the value of rm_service.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_service.name
     *
     * @param name the value for rm_service.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_service.description
     *
     * @return the value of rm_service.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_service.description
     *
     * @param description the value for rm_service.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_service.alias
     *
     * @return the value of rm_service.alias
     *
     * @mbggenerated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_service.alias
     *
     * @param alias the value for rm_service.alias
     *
     * @mbggenerated
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_service.typeId
     *
     * @return the value of rm_service.typeId
     *
     * @mbggenerated
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_service.typeId
     *
     * @param typeid the value for rm_service.typeId
     *
     * @mbggenerated
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rm_service.displayOrder
     *
     * @return the value of rm_service.displayOrder
     *
     * @mbggenerated
     */
    public Integer getDisplayorder() {
        return displayorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rm_service.displayOrder
     *
     * @param displayorder the value for rm_service.displayOrder
     *
     * @mbggenerated
     */
    public void setDisplayorder(Integer displayorder) {
        this.displayorder = displayorder;
    }
}