package com.csoft.resource.cflow.mapper;

import com.csoft.resource.cflow.pojo.CfHistoryInstanceTask;
import com.csoft.resource.cflow.pojo.CfHistoryInstanceTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfHistoryInstanceTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_task
     *
     * @mbggenerated
     */
    int countByExample(CfHistoryInstanceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_task
     *
     * @mbggenerated
     */
    int deleteByExample(CfHistoryInstanceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_task
     *
     * @mbggenerated
     */
    int insert(CfHistoryInstanceTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_task
     *
     * @mbggenerated
     */
    int insertSelective(CfHistoryInstanceTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_task
     *
     * @mbggenerated
     */
    List<CfHistoryInstanceTask> selectByExample(CfHistoryInstanceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_task
     *
     * @mbggenerated
     */
    CfHistoryInstanceTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_task
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfHistoryInstanceTask record, @Param("example") CfHistoryInstanceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_task
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfHistoryInstanceTask record, @Param("example") CfHistoryInstanceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfHistoryInstanceTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CfHistoryInstanceTask record);
}