package com.csoft.resource.cflow.mapper;

import com.csoft.resource.cflow.pojo.CfHistoryInstanceProcess;
import com.csoft.resource.cflow.pojo.CfHistoryInstanceProcessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfHistoryInstanceProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_process
     *
     * @mbggenerated
     */
    int countByExample(CfHistoryInstanceProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_process
     *
     * @mbggenerated
     */
    int deleteByExample(CfHistoryInstanceProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_process
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_process
     *
     * @mbggenerated
     */
    int insert(CfHistoryInstanceProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_process
     *
     * @mbggenerated
     */
    int insertSelective(CfHistoryInstanceProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_process
     *
     * @mbggenerated
     */
    List<CfHistoryInstanceProcess> selectByExample(CfHistoryInstanceProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_process
     *
     * @mbggenerated
     */
    CfHistoryInstanceProcess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_process
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfHistoryInstanceProcess record, @Param("example") CfHistoryInstanceProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_process
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfHistoryInstanceProcess record, @Param("example") CfHistoryInstanceProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_process
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfHistoryInstanceProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_process
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CfHistoryInstanceProcess record);
}