package com.csoft.resource.cflow.mapper;

import com.csoft.resource.cflow.pojo.CfHistoryInstanceInputValue;
import com.csoft.resource.cflow.pojo.CfHistoryInstanceInputValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfHistoryInstanceInputValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_input_value
     *
     * @mbggenerated
     */
    int countByExample(CfHistoryInstanceInputValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_input_value
     *
     * @mbggenerated
     */
    int deleteByExample(CfHistoryInstanceInputValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_input_value
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_input_value
     *
     * @mbggenerated
     */
    int insert(CfHistoryInstanceInputValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_input_value
     *
     * @mbggenerated
     */
    int insertSelective(CfHistoryInstanceInputValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_input_value
     *
     * @mbggenerated
     */
    List<CfHistoryInstanceInputValue> selectByExample(CfHistoryInstanceInputValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_input_value
     *
     * @mbggenerated
     */
    CfHistoryInstanceInputValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_input_value
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfHistoryInstanceInputValue record, @Param("example") CfHistoryInstanceInputValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_input_value
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfHistoryInstanceInputValue record, @Param("example") CfHistoryInstanceInputValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_input_value
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfHistoryInstanceInputValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_history_instance_input_value
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CfHistoryInstanceInputValue record);
}