package com.csoft.resource.cflow.mapper;

import com.csoft.resource.cflow.pojo.CfInstanceTask;
import com.csoft.resource.cflow.pojo.CfInstanceTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfInstanceTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_task
     *
     * @mbggenerated
     */
    int countByExample(CfInstanceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_task
     *
     * @mbggenerated
     */
    int deleteByExample(CfInstanceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_task
     *
     * @mbggenerated
     */
    int insert(CfInstanceTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_task
     *
     * @mbggenerated
     */
    int insertSelective(CfInstanceTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_task
     *
     * @mbggenerated
     */
    List<CfInstanceTask> selectByExample(CfInstanceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_task
     *
     * @mbggenerated
     */
    CfInstanceTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_task
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfInstanceTask record, @Param("example") CfInstanceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_task
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfInstanceTask record, @Param("example") CfInstanceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfInstanceTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CfInstanceTask record);
}