package com.csoft.resource.cflow.mapper;

import com.csoft.resource.cflow.pojo.CfInstanceInputValue;
import com.csoft.resource.cflow.pojo.CfInstanceInputValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfInstanceInputValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_input_value
     *
     * @mbggenerated
     */
    int countByExample(CfInstanceInputValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_input_value
     *
     * @mbggenerated
     */
    int deleteByExample(CfInstanceInputValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_input_value
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_input_value
     *
     * @mbggenerated
     */
    int insert(CfInstanceInputValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_input_value
     *
     * @mbggenerated
     */
    int insertSelective(CfInstanceInputValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_input_value
     *
     * @mbggenerated
     */
    List<CfInstanceInputValue> selectByExample(CfInstanceInputValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_input_value
     *
     * @mbggenerated
     */
    CfInstanceInputValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_input_value
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfInstanceInputValue record, @Param("example") CfInstanceInputValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_input_value
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfInstanceInputValue record, @Param("example") CfInstanceInputValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_input_value
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfInstanceInputValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_input_value
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CfInstanceInputValue record);
}