package com.csoft.resource.cflow.mapper;

import com.csoft.resource.cflow.pojo.CfInstanceProcess;
import com.csoft.resource.cflow.pojo.CfInstanceProcessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfInstanceProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_process
     *
     * @mbggenerated
     */
    int countByExample(CfInstanceProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_process
     *
     * @mbggenerated
     */
    int deleteByExample(CfInstanceProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_process
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_process
     *
     * @mbggenerated
     */
    int insert(CfInstanceProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_process
     *
     * @mbggenerated
     */
    int insertSelective(CfInstanceProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_process
     *
     * @mbggenerated
     */
    List<CfInstanceProcess> selectByExample(CfInstanceProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_process
     *
     * @mbggenerated
     */
    CfInstanceProcess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_process
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfInstanceProcess record, @Param("example") CfInstanceProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_process
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfInstanceProcess record, @Param("example") CfInstanceProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_process
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfInstanceProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_instance_process
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CfInstanceProcess record);
}